# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [34]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

height = np.array([69, 70, 71, 72, 73, 74, 75])
weight = np.array([110, 120, 130, 140, 150, 160, 170])
result = weight / (height**2) * 730
result


array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [42]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
#def makeMatrix(low,high,shape,data_type = float): -- Example

def makeMatrix(low, high, shape):
    return np.random.uniform(low, high, shape)
makeMatrix(10, 15, (9, 3))


array([[10.92600366, 14.5318646 , 13.55896551],
       [13.7434565 , 10.95595371, 12.98453089],
       [11.63788318, 12.57153028, 11.44625662],
       [12.86783279, 12.68378751, 14.97221881],
       [14.18640708, 13.43636098, 12.91802493],
       [13.28149002, 14.26482182, 13.37735129],
       [10.10104107, 12.24748422, 10.1748233 ],
       [13.51959513, 11.50810658, 13.92024098],
       [13.34706012, 12.55105495, 10.115581  ]])

### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [43]:
import csv
import numpy as np

#Test to make sure you have the correct data



In [49]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def open_csv(filename, d = ','):
    # define empty list to store data in
    data = []
    
    with open(filename, encoding = 'utf-8') as mData:
        # use csv to create a python list
        info = csv.reader(mData, delimiter=d)
        
        #Loop over info and append to data list
        for row in info:
            data.append(row)
    return data
csv_data = open_csv('./././././redsox_2017_hitting.csv')
print(csv_data[1:5])


FileNotFoundError: [Errno 2] No such file or directory: './././././redsox_2017_hitting.csv'